/* eslint-disable no-undef */

export const aspectRatioPressets = [
  {
    id: 'aspect-ratio-custom',
    name: 'Custom',
    width: NaN,
    height: NaN
  },
  {
    id: 'aspect-ratio-11',
    name: 'Rectangle 1:1',
    width: 1,
    height: 1,
    orientation: 'square',
  },
  {
    id: 'aspect-ratio-43',
    name: 'Landscape 4:3',
    width: 4,
    height: 3,
    orientation: 'landscape',
  },
  {
    id: 'aspect-ratio-54',
    name: 'Landscape 5:4',
    width: 5,
    height: 4,
    orientation: 'landscape',
  },
  {
    id: 'aspect-ratio-32',
    name: 'Landscape 3:2',
    width: 3,
    height: 2,
    orientation: 'landscape',
  },
  {
    id: 'aspect-ratio-53',
    name: 'Landscape 5:3',
    width: 5,
    height: 3,
    orientation: 'landscape',
  },
  {
    id: 'aspect-ratio-169',
    name: 'Landscape 16:9',
    width: 16,
    height: 9,
    orientation: 'landscape',
  },
  {
    id: 'aspect-ratio-31',
    name: 'Landscape 3:1',
    width: 16,
    height: 9,
    orientation: 'landscape',
  },
  {
    id: 'aspect-ratio-13',
    name: 'Portrait 1:3',
    width: 1,
    height: 3,
    orientation: 'landscape',
  },
  {
    id: 'aspect-ratio-34',
    name: 'Portrait 3:4',
    width: 3,
    height: 4,
    orientation: 'portrait',
  },
  {
    id: 'aspect-ratio-35',
    name: 'Portrait 3:5',
    width: 3,
    height: 5,
    orientation: 'portrait',
  },
  {
    id: 'aspect-ratio-45',
    name: 'Portrait 4:5',
    width: 4,
    height: 5,
    orientation: 'portrait',
  },
  {
    id: 'aspect-ratio-916',
    name: 'Portrait 9:16',
    width: 9,
    height: 16,
    orientation: 'portrait',
  },
  {
    id: 'aspect-ratio-23',
    name: 'Portrait 2:3',
    width: 2,
    height: 3,
    orientation: 'portrait',
  },
  {
    id: 'aspect-ratio-youtube-thumbnail',
    name: 'Youtube - Thumbnail',
    width: 16,
    height: 9,
    orientation: 'landscape',
  },
  {
    id: 'aspect-ratio-youtube-channel',
    name: 'Youtube - Channel',
    width: 16,
    height: 9,
    orientation: 'landscape',
  },
  {
    id: 'aspect-ratio-youtube-profile',
    name: 'Youtube - Profile',
    width: 1,
    height: 1,
    orientation: 'square',
  },
];
