name: Deploy to Firebase Functions on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v2
      - name: Install firebase-tools
        run: npm install firebase-tools
      - name: Install npm packages
        run: |
          cd functions
          npm install
          npm audit fix
          npm install firebase-tools
      - name: Run tests
        run: |
          cd functions
          npm run test
      - name: Deploy to Firebase
        run: npm run deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
